(add-to-list 'load-path
	     (expand-file-name(concat user-emacs-directory "lisp")))

(setq custom-file (expand-file-name "custom.el" user-emacs-directory))

(require 'init-proxy)
(require 'init-ui)

(require 'init-packages)
(require 'init-kaomoji-title-bar)
(require 'init-aweshell)
(require 'init-copilot)
(require 'init-project)
(require 'init-lsp-bridge)
;;(require 'init-lsp-mode)
(require 'init-transient)
(require 'init-aidermacs)
(require 'init-editing)
(require 'init-programming)
(require 'init-magit)
(require 'init-dashboard)
(require 'init-smartparens)
(require 'init-sort-tab)
(require 'init-doom-modeline)
(require 'init-treemacs)
(require 'init-winum)
(require 'init-dired)
(require 'init-ivy)
;;(require 'init-eaf)
(require 'init-ace-window)
(require 'init-webdev)
(require 'init-popper)
(require 'init-vterm)
(require 'init-format)
(require 'init-alpha)
(require 'init-kde-blur)

(put 'narrow-to-region 'disabled nil)
